# [Info]
site_name: Men Kaixuan的个人网站 # 左上角标题
site_url: https://viobert.github.io/self_impro/
site_author: Men Kaixuan
site_description: Men Kaixuan的个人网站

# [UI]
## [top]
theme:
  name: material
  favicon: MEDIA/hat-wizard.svg
  palette: 
    - scheme: default # 日间模式
      primary: amber # 上方的
      accent: deep purple # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    # - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
  language: zh # 一些提示性的文字会变成中文
  icon:
    logo: fontawesome/solid/dragon
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/viobert/self_impro # 右上角点击跳转的链接
repo_name: viobert.github.io # 右上角的名字
## [bottom-left corner]
copyright: Copyright &copy; 2022 Men Kaixuan # 左下角的版权声明

# [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/358593321
      name: Bilibili | menmen庄园 # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/viobert
      name: GitHub | viobert

# [Navigtion]
nav:
  - Git:
    - GIT/index.md
    - Learn git: GIT/learnGit/git.md
    - Github pages: 
      - Getting started: GIT/ghPages/getting_started.md
      - Setup: GIT/ghPages/Setup.md
  - macOS: 
    - Alfred: MACOS/Alfred/alfred.md
  - Note:
    - NOTE/index.md
    - class notes:
      - Assembly Language: NOTE/class/Assembly Language.md 
      - Digital Image Processing: NOTE/class/Digital Image Processing.md
      - Disassembly And Reverse: NOTE/class/Disassembly And Reverse.md
      - Operating System: NOTE/class/Operating System.md
      - Network Programing: NOTE/class/Network Programing.md
    - socket: NOTE/socket/Socket.md
    - python: NOTE/python/Python.md
  - Machine learning:
    - MACHINE_LEARNING/index.md
    - d2l: MACHINE_LEARNING/Dive into Deep Learning.md
  - 奇怪的插班生:
    - ENGLISH/index.md
    - 语法: 
      - 语法学习路线一览: ENGLISH/grammar/grammarLearn.md 
      - 语法整体框架概括: ENGLISH/grammar/grammar_generalize.md 
      - 动词时态: ENGLISH/grammar/verbs_tense.md
      - 动词语气: ENGLISH/grammar/verb_moods.md
      - 非谓语动词: ENGLISH/grammar/non_finite_verbs.md
      - 独立主格: ENGLISH/grammar/absolute_construction.md
      - 助动词&情态动词: ENGLISH/grammar/auxiliary_modal_verbs.md
      - 系动词&使役动词: ENGLISH/grammar/linking_verbs.md
      - 从句: ENGLISH/grammar/clause.md
    - reading:
      - Why economists are flocking to Silicon Valley: ENGLISH/reading/Why economists are flocking to Silicon Valley.md
      - Coding is still a good career bet: ENGLISH/reading/Coding is still a good career bet.md
      - chatGPT: ENGLISH/reading/chatGPT.md
      - Frog and Princes: ENGLISH/reading/Frog and Princes.md
  - 玻璃球:
    - IMPROVEMENTS/index.md
    - 探索者计划: IMPROVEMENTS/Explorer Program.md
    - Experience: 
      - YOLO: IMPROVEMENTS/scientific_research_experience/YOLO v6.md
  - 文摘:
    - SUMMARY/index.md
    - ドラゴン桜: SUMMARY/doragon_zakura.md
    - Agatha Christie: SUMMARY/Agatha Christie.md
    - Alfred Hitchcock: SUMMARY/Alfred Hitchcock.md
    - Recommend: SUMMARY/splendid_film.md
  - 孤独的美食“家”:
    - GOURMET/index.md
    - 脆皮五花肉: GOURMET/streaky_pork.md


# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
markdown_extensions:
  - pymdownx.caret   # highlight text support 下划线
  - pymdownx.mark    # highlight text support 背景高亮
  - pymdownx.tilde   # highlight text support 中划线
  - pymdownx.keys    # 键盘标识
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols

